#!/usr/bin/env python3
import base64
import hashlib
import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization


os.environ["LSA_DATABASE_URL"] = "sqlite:////tmp/lsa-integration.sqlite3"
os.environ["LSA_BOOTSTRAP_PASSWORD"] = "integration-password"
os.environ["LSA_SESSION_SECRET"] = "integration-session-secret-with-32-characters"

def verify(
    output_root: Path,
    hostname: str = "debian13-ci",
    expected_family: str = "debian",
    expected_version: str = "13",
    expected_findings: int = 358,
) -> None:
    from fastapi.testclient import TestClient

    from lsa.database import SessionLocal
    from lsa.main import app
    from lsa.models import SigningKey, Tenant
    from lsa.schemas import ReportInput
    from lsa.seed import DEMO_TOKEN

    host_dir = output_root / hostname / "pending"
    report_path = host_dir / "report.json"
    bundle_paths = sorted(host_dir.glob("lsa-report-*.zip"))
    if not report_path.exists() or len(bundle_paths) != 1:
        raise RuntimeError("Scanner did not produce one report and one portable bundle")

    report = ReportInput.model_validate(json.loads(report_path.read_text()))
    control_ids = [finding.control_id for finding in report.findings]
    if report.host.os_family != expected_family or not report.host.os_version.startswith(expected_version):
        raise RuntimeError(f"Integration report was not generated by {expected_family} {expected_version}")
    if report.scan.profile != "level2_server":
        raise RuntimeError("Integration report did not preserve the selected profile")
    if len(control_ids) != expected_findings or len(control_ids) != len(set(control_ids)):
        raise RuntimeError(
            f"Integration report does not contain {expected_findings} unique controls: {len(control_ids)}"
        )
    if report.summary.not_applicable == 0:
        raise RuntimeError("Profile-excluded controls were not retained as not applicable")

    with TestClient(app) as client:
        with SessionLocal() as db:
            tenant = db.query(Tenant).first()
            private_key = serialization.load_pem_private_key(
                Path("/tmp/lsa-integration-signing-key.pem").read_bytes(), password=None
            )
            public_key = private_key.public_key().public_bytes(
                serialization.Encoding.Raw,
                serialization.PublicFormat.Raw,
            )
            db.add(
                SigningKey(
                    id="00000000-0000-4000-8000-000000009001",
                    tenant_id=tenant.id,
                    name=f"{expected_family} {expected_version} CI signer",
                    public_key=base64.b64encode(public_key).decode(),
                    fingerprint=hashlib.sha256(public_key).hexdigest(),
                )
            )
            db.commit()
        response = client.post(
            "/api/v1/ingest/bundles",
            headers={"Authorization": f"Bearer {DEMO_TOKEN}"},
            files={"file": (bundle_paths[0].name, bundle_paths[0].read_bytes(), "application/zip")},
        )
    if response.status_code != 202:
        raise RuntimeError(f"Generated bundle was rejected: {response.status_code} {response.text}")
    if response.json()["findings_imported"] != expected_findings:
        raise RuntimeError("Ingestion did not persist every generated finding")


if __name__ == "__main__":
    if len(sys.argv) not in {2, 6}:
        raise SystemExit(
            "usage: verify_debian13_integration.py OUTPUT_ROOT "
            "[HOSTNAME EXPECTED_FAMILY EXPECTED_VERSION EXPECTED_FINDINGS]"
        )
    if len(sys.argv) == 2:
        verify(Path(sys.argv[1]))
    else:
        verify(Path(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4], int(sys.argv[5]))
