#!/usr/bin/env python3
import base64
import hashlib
import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization


os.environ["LSA_DATABASE_URL"] = "sqlite:////tmp/lsa-integration.sqlite3"
os.environ["LSA_BOOTSTRAP_PASSWORD"] = "integration-password"
os.environ["LSA_SESSION_SECRET"] = "integration-session-secret-with-32-characters"

def verify(output_root: Path) -> None:
    from fastapi.testclient import TestClient

    from lsa.database import SessionLocal
    from lsa.main import app
    from lsa.models import SigningKey, Tenant
    from lsa.schemas import ReportInput
    from lsa.seed import DEMO_TOKEN

    host_dir = output_root / "debian13-ci" / "pending"
    report_path = host_dir / "report.json"
    bundle_paths = sorted(host_dir.glob("lsa-report-*.zip"))
    if not report_path.exists() or len(bundle_paths) != 1:
        raise RuntimeError("Scanner did not produce one report and one portable bundle")

    report = ReportInput.model_validate(json.loads(report_path.read_text()))
    control_ids = [finding.control_id for finding in report.findings]
    if report.host.os_family != "debian" or not report.host.os_version.startswith("13"):
        raise RuntimeError("Integration report was not generated by Debian 13")
    if report.scan.profile != "container":
        raise RuntimeError("Integration report did not preserve the selected profile")
    if len(control_ids) != 32 or len(control_ids) != len(set(control_ids)):
        raise RuntimeError("Integration report does not contain 32 unique controls")
    if report.summary.not_applicable == 0:
        raise RuntimeError("Container profile did not mark service controls as not applicable")

    with TestClient(app) as client:
        with SessionLocal() as db:
            tenant = db.query(Tenant).first()
            private_key = serialization.load_pem_private_key(
                Path("/tmp/lsa-integration-signing-key.pem").read_bytes(), password=None
            )
            public_key = private_key.public_key().public_bytes(
                serialization.Encoding.Raw,
                serialization.PublicFormat.Raw,
            )
            db.add(
                SigningKey(
                    id="00000000-0000-4000-8000-000000009001",
                    tenant_id=tenant.id,
                    name="Debian 13 CI signer",
                    public_key=base64.b64encode(public_key).decode(),
                    fingerprint=hashlib.sha256(public_key).hexdigest(),
                )
            )
            db.commit()
        response = client.post(
            "/api/v1/ingest/bundles",
            headers={"Authorization": f"Bearer {DEMO_TOKEN}"},
            files={"file": (bundle_paths[0].name, bundle_paths[0].read_bytes(), "application/zip")},
        )
    if response.status_code != 202:
        raise RuntimeError(f"Generated bundle was rejected: {response.status_code} {response.text}")
    if response.json()["findings_imported"] != 32:
        raise RuntimeError("Ingestion did not persist every generated finding")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: verify_debian13_integration.py OUTPUT_ROOT")
    verify(Path(sys.argv[1]))
